### ISSUE TITLE
QA Staging Environment

### ISSUE THREAD

**Issue by oneEdoubleD** [input-output-hk/cardano-ops#10]
Could QA have a staging environment where we can set up small clusters of distributed nodes (over multiple regions and/or zones) to perform system level testing? We'd need to be able to update these nodes, access their logs, and run the transaction-generator. I think a clone of the existing staging server would be suitable.

**Comment by disassembler** [comment]
Awaiting a PR to update ssh keys in iohk-ops

**Comment by oneEdoubleD** [comment]
@disassembler - I've made a PR to add my SSH keys to iohk-ops

**Comment by alan-mcnicholas** [comment]
Do we need any additional sign off\discussion on this?

**Comment by disassembler** [comment]
@oneEdoubleD should have access to dev deployer which has staging-shelley deployment on there.
