### ISSUE TITLE
Propagate agreed upon changes to `cardano-node` cli

### ISSUE THREAD

**Issue by Jimbo4350** [input-output-hk/cardano-ops#35]
There are cli change requests from different teams that need to be agreed upon and propagated to the relevant nix derivations. [PR #335](https://github.com/input-output-hk/cardano-node/pull/335) contains the following

- Specification of a `socket-path` instead of a `socket-dir`.
- Removal of `NodeId` from the topology file.
- Addition of `run`/`run-mock` parsers to the command line to enable selection between mock and real protocols.

**Comment by disassembler** [comment]
this is not related to cardano-ops
