### ISSUE TITLE
Provide developer access to redeploy short and normal epoch clusters

### ISSUE THREAD

**Issue by dcoutts** [input-output-hk/cardano-ops#9]
As discussed, QA and certain devs would need access to the short-epoch cluster, and normal-epoch cluster for integration testing.

So the task is to make both of these clusters available from the existing deployment machine that the developers have ssh access to.

Some QA and devs may not yet be aware of the docs for the deployment machine, or the list of ssh keys. It would be worth pointing out again to them exactly where the docs are, and the ssh key list.

**Comment by disassembler** [comment]
Awaiting a PR to update ssh keys in iohk-ops
